---
- name: Create Azure Service Principal
  hosts: localhost
  collections:
    - azure.azcollection
  vars:
    tenant_id: df49ebf2-2fd2-44c2-80f8-37058cc147b9 
    spnName: "ansible-created-Rahul"
    secretvalue: 82e430b4-87dc-4c42-a14c-48fd96d26d0d
  tasks:
    - name: Create ad application
      azure_rm_adapplication:
        tenant: "{{tenant_id}}"
        display_name: "{{spnName}}"
        # secret: "exS8Q~yJ1ChsMqf6BEXZB5WKaah2aKrtV.l7rc_x"
        password: "{{ secretvalue }}"
        state: "present"
      register: entraid_app

    - debug: msg={{entraid_app}}