# - hosts: localhost
#   gather_facts: false
#   connection: local
#   collections:
#     - azure.azcollection
#   vars:
#     tenant_id: "{{ tenant_id }}"
#     svcname: "{{svcname}}"
#     upnpostfix: "@rgtechlabsoutlook.onmicrosoft.com" 
  # tasks:
- name: Creating ServiceAccount {{ svcname }}
  azure_rm_aduser:
    user_principal_name: "{{ svcname }}@rgtechlabsoutlook.onmicrosoft.com"
    tenant: "df49ebf2-2fd2-44c2-80f8-37058cc147b9"
    state: "present"
    account_enabled: "True"
    display_name: "{{ svcname }}"
    password_profile: "I@mUtoPi@N"
    mail_nickname: "{{ svcname }}"
    given_name: "{{ svcname }}"
    # surname: ""
    user_type: "Member"
    # usage_location: ""
    # mail: "{{ svcname }}{{ upnpostfix }}"