# - hosts: localhost
#   connection: local
#   collections:
#     - azure.azcollection
  # vars:
  #   tenant_id: "{{tenant_id}}"
  #   AllAdmingroupcreate: "{{ AllAdmingroupcreate }}"

  # tasks:

- name: Creating Azure AD Security Group {{ AllAdmingroupcreate }}
  azure_rm_adgroup:
    tenant: "df49ebf2-2fd2-44c2-80f8-37058cc147b9"
    display_name: "{{ AllAdmingroupcreate }}"
    mail_nickname: "{{ AllAdmingroupcreate }}"
    state: 'present'
  register: AllAdmingroupcreate_result

- debug: msg="{{ AllAdmingroupcreate_result }}"
