# - hosts: localhost
#   connection: local
#   collections:
#     - azure.azcollection
  vars:
    tenant_id: "{{tenant_id}}"
    AllAdmingroupcreate: "{{ AllAdmingroupcreate }}"

  tasks:
    - name: Creating Azure AD Security Group {{ AllAdmingroupcreate }}
      azure.azcollection.azure_rm_adgroup:
        tenant: "{{tenant_id}}"
        display_name: "{{ AllAdmingroupcreate }}"
        mail_nickname: "{{ AllAdmingroupcreate }}"
        state: 'present'
      register: AllAdmingroupcreate_result

    - debug: msg="{{ AllAdmingroupcreate_result }}"
