---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - azure.azcollection
  vars:
    user_emailId: "naresh@rgtechlabsoutlook.onmicrosoft.com"
  tasks:
  - name: Using user_principal_name
    azure.azcollection.azure_rm_aduser_info:
      user_principal_name: "{{ user_emailId }}"
      tenant: "df49ebf2-2fd2-44c2-80f8-37058cc147b9"
    register: sp_result

  - debug: msg="{{sp_result}}"
